services:
  endee-server:
    image: endeeio/endee-server:latest
    container_name: endee-server
    ports:
      - "8080:8080"
    ulimits:
      nofile: 100000
    volumes:
      - ./endee-data:/data
    restart: unless-stopped
